#ifndef AMMONITEKEYCODES
#define AMMONITEKEYCODES

#include <cstdint>

/*
 - Values match corresponding values in GLFW
 - Redefined here to avoid client code including GLFW headers
*/
//NOLINTBEGIN(misc-confusable-identifiers)
enum AmmoniteKeycode : int16_t {
  AMMONITE_UNKNOWN       = -1,

  //Printable characters
  AMMONITE_SPACE         = 32,
  AMMONITE_APOSTROPHE    = 39,
  AMMONITE_COMMA         = 44,
  AMMONITE_MINUS         = 45,
  AMMONITE_FULLSTOP      = 46,
  AMMONITE_FORWARDSLASH  = 47,
  AMMONITE_0             = 48,
  AMMONITE_1             = 49,
  AMMONITE_2             = 50,
  AMMONITE_3             = 51,
  AMMONITE_4             = 52,
  AMMONITE_5             = 53,
  AMMONITE_6             = 54,
  AMMONITE_7             = 55,
  AMMONITE_8             = 56,
  AMMONITE_9             = 57,
  AMMONITE_SEMICOLON     = 59,
  AMMONITE_EQUAL         = 61,
  AMMONITE_A             = 65,
  AMMONITE_B             = 66,
  AMMONITE_C             = 67,
  AMMONITE_D             = 68,
  AMMONITE_E             = 69,
  AMMONITE_F             = 70,
  AMMONITE_G             = 71,
  AMMONITE_H             = 72,
  AMMONITE_I             = 73,
  AMMONITE_J             = 74,
  AMMONITE_K             = 75,
  AMMONITE_L             = 76,
  AMMONITE_M             = 77,
  AMMONITE_N             = 78,
  AMMONITE_O             = 79,
  AMMONITE_P             = 80,
  AMMONITE_Q             = 81,
  AMMONITE_R             = 82,
  AMMONITE_S             = 83,
  AMMONITE_T             = 84,
  AMMONITE_U             = 85,
  AMMONITE_V             = 86,
  AMMONITE_W             = 87,
  AMMONITE_X             = 88,
  AMMONITE_Y             = 89,
  AMMONITE_Z             = 90,
  AMMONITE_LEFT_BRACKET  = 91,
  AMMONITE_BACKSLASH     = 92,
  AMMONITE_RIGHT_BRACKET = 93,
  AMMONITE_GRAVE_ACCENT  = 96,
  AMMONITE_WORLD_1       = 161, /* non-US #1 */
  AMMONITE_WORLD_2       = 162, /* non-US #2 */

  //Function keys
  AMMONITE_ESCAPE        = 256,
  AMMONITE_ENTER         = 257,
  AMMONITE_TAB           = 258,
  AMMONITE_BACKSPACE     = 259,
  AMMONITE_INSERT        = 260,
  AMMONITE_DELETE        = 261,
  AMMONITE_RIGHT         = 262,
  AMMONITE_LEFT          = 263,
  AMMONITE_DOWN          = 264,
  AMMONITE_UP            = 265,
  AMMONITE_PAGE_UP       = 266,
  AMMONITE_PAGE_DOWN     = 267,
  AMMONITE_HOME          = 268,
  AMMONITE_END           = 269,
  AMMONITE_CAPS_LOCK     = 280,
  AMMONITE_SCROLL_LOCK   = 281,
  AMMONITE_NUM_LOCK      = 282,
  AMMONITE_PRINT_SCREEN  = 283,
  AMMONITE_PAUSE         = 284,
  AMMONITE_F1            = 290,
  AMMONITE_F2            = 291,
  AMMONITE_F3            = 292,
  AMMONITE_F4            = 293,
  AMMONITE_F5            = 294,
  AMMONITE_F6            = 295,
  AMMONITE_F7            = 296,
  AMMONITE_F8            = 297,
  AMMONITE_F9            = 298,
  AMMONITE_F10           = 299,
  AMMONITE_F11           = 300,
  AMMONITE_F12           = 301,
  AMMONITE_F13           = 302,
  AMMONITE_F14           = 303,
  AMMONITE_F15           = 304,
  AMMONITE_F16           = 305,
  AMMONITE_F17           = 306,
  AMMONITE_F18           = 307,
  AMMONITE_F19           = 308,
  AMMONITE_F20           = 309,
  AMMONITE_F21           = 310,
  AMMONITE_F22           = 311,
  AMMONITE_F23           = 312,
  AMMONITE_F24           = 313,
  AMMONITE_F25           = 314,
  AMMONITE_KP_0          = 320,
  AMMONITE_KP_1          = 321,
  AMMONITE_KP_2          = 322,
  AMMONITE_KP_3          = 323,
  AMMONITE_KP_4          = 324,
  AMMONITE_KP_5          = 325,
  AMMONITE_KP_6          = 326,
  AMMONITE_KP_7          = 327,
  AMMONITE_KP_8          = 328,
  AMMONITE_KP_9          = 329,
  AMMONITE_KP_DECIMAL    = 330,
  AMMONITE_KP_DIVIDE     = 331,
  AMMONITE_KP_MULTIPLY   = 332,
  AMMONITE_KP_SUBTRACT   = 333,
  AMMONITE_KP_ADD        = 334,
  AMMONITE_KP_ENTER      = 335,
  AMMONITE_KP_EQUAL      = 336,
  AMMONITE_LEFT_SHIFT    = 340,
  AMMONITE_LEFT_CONTROL  = 341,
  AMMONITE_LEFT_ALT      = 342,
  AMMONITE_LEFT_SUPER    = 343,
  AMMONITE_RIGHT_SHIFT   = 344,
  AMMONITE_RIGHT_CONTROL = 345,
  AMMONITE_RIGHT_ALT     = 346,
  AMMONITE_RIGHT_SUPER   = 347,
  AMMONITE_MENU          = 348,

  AMMONITE_LAST          = AMMONITE_MENU
};
//NOLINTEND(misc-confusable-identifiers)

#endif
