# This workflow will build and test the thread pool
name: Thread pool test

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install build dependencies
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy main" | sudo tee -a /etc/apt/sources.list
        sudo apt-get update
        sudo apt-get install --no-install-recommends make pkg-config build-essential
        sudo apt-get install --no-install-recommends g++-12 clang-19
        sudo apt-get install --no-install-recommends inkscape optipng
        sudo apt-get install --no-install-recommends libglm-dev libglfw3-dev libglew-dev libstb-dev libassimp-dev
        sudo apt-get install --no-install-recommends valgrind
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 10000
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-19 10000
        sudo update-alternatives --set g++ /usr/bin/g++-12
        sudo update-alternatives --set clang++ /usr/bin/clang++-19

    - name: (g++) Test thread demo build target
      run: |
        make clean
        CXX="g++" DEBUG="true" make threads -j$(nproc)

    - name: (g++) Test built thread demo
      run: |
        ./launch.sh --threads

    - name: (g++) (valgrind) Test built thread demo
      run: |
        LD_LIBRARY_PATH=build valgrind --fair-sched=yes --leak-check=full --show-leak-kinds=all --error-exitcode=1 ./build/threadDemo

    - name: (clang++) Test thread demo build target
      run: |
        make clean
        CXX="clang++" DEBUG="true" make threads -j$(nproc)

    - name: (clang++) (valgrind) Test built thread demo
      run: |
        LD_LIBRARY_PATH=build valgrind --fair-sched=yes --leak-check=full --show-leak-kinds=all --error-exitcode=1 ./build/threadDemo
