# This workflow will build and test the thread pool
name: Thread pool test

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install build dependencies
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        echo "deb http://apt.llvm.org/noble/ llvm-toolchain-noble-19 main" | sudo tee -a /etc/apt/sources.list
        sudo apt-get update
        sudo apt-get install --no-install-recommends make pkg-config build-essential
        sudo apt-get install g++-14 clang-19
        sudo apt-get install --no-install-recommends libglm-dev libglfw3-dev libglew-dev libstb-dev libassimp-dev

    - name: (g++) (DEBUG) Build thread tester
      run: |
        make clean
        CXX="g++-14" DEBUG="true" make threads -j$(nproc)

    - name: (g++) (DEBUG) Run thread tester
      run: |
        ./launch.sh --threads

    - name: (g++) (CHECK_THREADS) Build thread tester
      run: |
        make clean
        CXX="g++-14" CHECK_THREADS="true" make threads -j$(nproc)

    - name: (g++) (CHECK_THREADS) Run thread tester
      run: |
        ./launch.sh --threads

    - name: (clang++) (DEBUG) Build thread tester
      run: |
        make clean
        CXX="clang++-19" DEBUG="true" make threads -j$(nproc)

    - name: (clang++) (DEBUG) Run thread tester
      run: |
        ./launch.sh --threads

    - name: (clang++) (CHECK_THREADS) Build thread tester
      run: |
        make clean
        CXX="clang++-19" CHECK_THREADS="true" make threads -j$(nproc)

    - name: (clang++) (CHECK_THREADS) Run thread tester
      run: |
        ./launch.sh --threads
