# This workflow will build and test the thread pool
name: Thread pool test

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends make pkg-config build-essential
        sudo apt-get install --no-install-recommends g++-14 clang-18
        sudo apt-get install --no-install-recommends libglm-dev libglfw3-dev libglew-dev libstb-dev libassimp-dev
        sudo apt-get install --no-install-recommends valgrind

    - name: (g++) Test thread demo build target
      run: |
        make clean
        CXX="g++-14" DEBUG="true" make threads -j$(nproc)

    - name: (g++) Test built thread demo
      run: |
        ./launch.sh --threads

    - name: (g++) (valgrind) Test built thread demo
      run: |
        LD_LIBRARY_PATH=build valgrind --fair-sched=yes --leak-check=full --show-leak-kinds=all --error-exitcode=1 ./build/threadDemo

    - name: (clang++) Test thread demo build target
      run: |
        make clean
        CXX="clang++-18" DEBUG="true" make threads -j$(nproc)

    - name: (clang++) (valgrind) Test built thread demo
      run: |
        LD_LIBRARY_PATH=build valgrind --fair-sched=yes --leak-check=full --show-leak-kinds=all --error-exitcode=1 ./build/threadDemo
