# This workflow will build and test the thread pool
name: Thread pool test

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends make pkg-config build-essential
        sudo apt-get install --no-install-recommends g++-14 clang-18
        sudo apt-get install --no-install-recommends libglm-dev libglfw3-dev libglew-dev libstb-dev libassimp-dev

    - name: (g++) (DEBUG) Build thread tester
      run: |
        make clean
        CXX="g++-14" DEBUG="true" make threads -j$(nproc)

    - name: (g++) (DEBUG) Run thread tester
      run: |
        ./launch.sh --threads

    - name: (g++) (CHECK_THREADS) Build thread tester
      run: |
        make clean
        CXX="g++-14" CHECK_THREADS="true" make threads -j$(nproc)

    - name: (g++) (CHECK_THREADS) Run thread tester
      run: |
        ./launch.sh --threads

    - name: (clang++) (DEBUG) Build thread tester
      run: |
        make clean
        CXX="clang++-14" DEBUG="true" make threads -j$(nproc)

    - name: (clang++) (DEBUG) Run thread tester
      run: |
        ./launch.sh --threads

    - name: (clang++) (CHECK_THREADS) Build thread tester
      run: |
        make clean
        CXX="clang++-14" CHECK_THREADS="true" make threads -j$(nproc)

    - name: (clang++) (CHECK_THREADS) Run thread tester
      run: |
        ./launch.sh --threads
