# This workflow will build and test the engine
name: Engine tests

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [{runner: ubuntu-26.04, arch: x86-64}, {runner: ubuntu-26.04-arm, arch: unset}]
        compiler: [{package: g++-16, command: g++-16}, {package: clang-19, command: clang++-19}]
        stdlib: [libstdc++-16-dev]
    runs-on: ${{ matrix.os.runner }}
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name


    steps:
    - uses: actions/checkout@v7
      with:
        submodules: 'recursive'
    - name: Set up Python 3.14
      uses: actions/setup-python@v7
      with:
        python-version: '3.14'

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends make pkg-config
        sudo apt-get install ${{ matrix.compiler.package }} ${{ matrix.stdlib }}
        sudo apt-get install --no-install-recommends libglm-dev libglfw3-dev libepoxy-dev libstb-dev libassimp-dev

    - name: Set up libtangle
      run: |
        make -C libtangle build -j$(nproc)

    - name: (DEBUG + ASan + UBSan) Build tests
      run: |
        make clean
        ARCH="${{ matrix.os.arch }}" CXX="${{ matrix.compiler.command }}" DEBUG="true" make tests -j$(nproc)

    - name: (DEBUG + ASan + UBSan) Run maths tester
      run: |
        ./launch.sh --maths
